var Smilies = {
    'My Little Pony': [
        ['Mad', 'http://i.imgur.com/f3h2mxR.png'],
        ['Grin', 'http://i.imgur.com/W7PH69O.png'],
        ['Annoy', 'http://i.imgur.com/W259ngj.png'],
        ['Shock', 'http://i.imgur.com/zXISgZ0.png'],
        ['Whine', 'http://i.imgur.com/iaOfndZ.png'],
        ['Shrug', 'http://i.imgur.com/iTHheSO.png'],
        ['Squint', 'http://i.imgur.com/NsPFjxI.png'],
        ['Derp', 'http://i.imgur.com/k7MPAR9.png'],
        ['Shock', 'http://i.imgur.com/vKDXgbI.png'],
        ['Awesome', 'http://i.imgur.com/ai92VCU.png'],
        ['Squint2', 'http://i.imgur.com/qx6KPUA.png'],
        ['Sad', 'http://i.imgur.com/hXZikdq.png'],
        ['Supersad', 'http://i.imgur.com/Eu4f62W.png'],
        ['Sad2', 'http://i.imgur.com/RotCs9S.png'],
        ['Scared', 'http://i.imgur.com/hy2KXYd.png'],
        ['Huh', 'http://i.imgur.com/gMoKl0C.png'],
        ['Crown', 'http://i.imgur.com/ZYRc3Je.png'],
        ['Whine2', 'http://i.imgur.com/MP05T2k.png'],
        ['Winning', 'http://i.imgur.com/zeUdw32.png'],
        ['Yay', 'http://i.imgur.com/2nfJjhk.png'],
        ['Brohug', 'http://i.imgur.com/CvJaKoE.png'],
        ['Grouphug', 'http://i.imgur.com/B2SBfFJ.png'],
        ['Brohoof', 'http://i.imgur.com/pvZhLbL.png'],
        ['OOps', 'http://i.imgur.com/OQ6h4dP.png'],
        ['Ohgod', 'http://i.imgur.com/xXCK2JH.png'],
        ['Rage', 'http://i.imgur.com/wjF9YAg.png'],
        ['Moustache', 'http://i.imgur.com/djMfHp0.png'],
        ['Lol', 'http://i.imgur.com/DodceOg.png'],
        ['Wtf', 'http://i.imgur.com/7Yr9M2F.png'],
        ['You Don\'t Say', 'http://i.imgur.com/7kmX8DW.png'],
        ['Think', 'http://i.imgur.com/w4BMKS1.png'],
        ['Hipster', 'http://i.imgur.com/712rwl2.png'],
        ['Hipster', 'http://i.imgur.com/MWk0kKi.png'],
        ['Deal With It', 'http://i.imgur.com/88nYIYB.png'],
        ['Gasp', 'http://i.imgur.com/HDGVntS.png'],
        ['Rofl', 'http://i.imgur.com/ebwrO4w.png'],
        ['WIT', 'http://i.imgur.com/UaSFoYx.png'],
        ['Woah', 'http://i.imgur.com/S3uqtd9.png'],
        ['Deal With It', 'http://i.imgur.com/J62VTZ3.png'],
        ['Dark', 'http://i.imgur.com/O280v32.png'],
        ['Jedi', 'http://i.imgur.com/lW5PvfP.png'],
        ['Twist', 'http://i.imgur.com/M7lyV4d.png']
    ],
    'Rageicons': [
        ['actually', 'http://i.imgur.com/yJnfzCl.png'],
        ['aliens', 'http://i.imgur.com/nct5szo.jpg'],
        ['all', 'http://i.imgur.com/meXdtwY.png'],
        ['awesome', 'http://i.imgur.com/0ENwPkD.png'],
        ['awyeah', 'http://i.imgur.com/NJo4GVZ.png'],
        ['babytroll', 'http://i.imgur.com/ps4NQQW.png'],
        ['badass', 'http://i.imgur.com/BaKnDIW.png'],
        ['badpokerface', 'http://i.imgur.com/L3WD2Uw.png'],
        ['baww', 'http://i.imgur.com/mkJCNv4.png'],
        ['biggrin', 'http://i.imgur.com/XaChYu7.png'],
        ['cereal', 'http://i.imgur.com/jGkzAA5.png'],
        ['cerealspitting', 'http://i.imgur.com/y3vYMeq.png'],
        ['challengeaccepted', 'http://i.imgur.com/KvSqLC7.png'],
        ['citizen_cane', 'http://i.imgur.com/4MLejyD.gif'],
        ['clint', 'http://i.imgur.com/uN4VICk.gif'],
        ['closeenough', 'http://i.imgur.com/p3x0kar.png'],
        ['cochran', 'http://i.imgur.com/i4CD4gp.gif'],
        ['dance', 'http://i.imgur.com/SBVVC3L.gif'],
        ['datash', 'http://i.imgur.com/h6ZAr0z.jpg'],
        ['dealwithit', 'http://i.imgur.com/vapvzGG.gif'],
        ['derp', 'http://i.imgur.com/m7BJ4i6.png'],
        ['determined', 'http://i.imgur.com/HYWZFoO.png'],
        ['disgusted', 'http://i.imgur.com/D3DJdyj.png'],
        ['dolan', 'http://i.imgur.com/gsZuyy3.png'],
        ['dudecomeon', 'http://i.imgur.com/TOoP5Sx.png'],
        ['eddance', 'http://i.imgur.com/rdjzV9p.gif'],
        ['edgrin', 'http://i.imgur.com/MdAbF1K.gif'],
        ['ewbte', 'http://i.imgur.com/3AZOoq2.png'],
        ['excitedtroll', 'http://i.imgur.com/JzyIIxp.png'],
        ['falbulous', 'http://i.imgur.com/mYzGfHT.gif'],
        ['fapfap', 'http://i.imgur.com/uVXIuup.png'],
        ['feelsgood', 'http://i.imgur.com/Qn0neUF.png'],
        ['fffuuu', 'http://i.imgur.com/eMOYawM.png'],
        ['fffuuu-s', 'http://i.imgur.com/0agDevF.png'],
        ['flip', 'http://i.imgur.com/VW2sLjz.png'],
        ['foreveralone', 'http://i.imgur.com/wTUuZkX.png'],
        ['friends', 'http://i.imgur.com/wazjdvq.png'],
        ['fu', 'http://i.imgur.com/x7rC2c8.png'],
        ['fuckyea', 'http://i.imgur.com/HZhzjUQ.png'],
        ['fullpanel', 'http://i.imgur.com/2KUOck3.png'],
        ['fumanchu', 'http://i.imgur.com/Mr3Ppgs.jpg'],
        ['gasp', 'http://i.imgur.com/EPvK0Xy.png'],
        ['gaytroll', 'http://i.imgur.com/7JM5HMT.png'],
        ['god', 'http://i.imgur.com/PVFNMs4.png'],
        ['gtfo', 'http://i.imgur.com/0EyUSP5.png'],
        ['happy', 'http://i.imgur.com/luwPEBd.png'],
        ['hehehe', 'http://i.imgur.com/cJfuA5Y.png'],
        ['herpderp', 'http://i.imgur.com/4oC9fAx.png'],
        ['high', 'http://i.imgur.com/eRNflhP.png'],
        ['highexpectations', 'http://i.imgur.com/0Jn3Vpy.jpg'],
        ['iamdisappointed', 'http://i.imgur.com/f83qMYJ.png'],
        ['impossibru', 'http://i.imgur.com/IJsKgJZ.png'],
        ['itsnotokay', 'http://i.imgur.com/d4uQD52.png'],
        ['jackiechan', 'http://i.imgur.com/iGjHMWD.jpg'],
        ['kidding', 'http://i.imgur.com/kFeRAIY.png'],
        ['kobe', 'http://i.imgur.com/6xlbTeR.gif'],
        ['lied', 'http://i.imgur.com/JJHley0.png'],
        ['lod', 'http://i.imgur.com/Gg10Cps.jpg'],
        ['lolnotext', 'http://i.imgur.com/pd1wpqx.png'],
        ['mad', 'http://i.imgur.com/c0GpKlN.png'],
        ['megusta', 'http://i.imgur.com/RxVUbho.png'],
        ['melvin', 'http://i.imgur.com/wWlgCJg.png'],
        ['milk', 'http://i.imgur.com/Wmy5bRG.png'],
        ['mindblown', 'http://i.imgur.com/dmVMKtk.gif'],
        ['mouthopen', 'http://i.imgur.com/12RWbvW.png'],
        ['newspaperguy', 'http://i.imgur.com/eSXzUe7.png'],
        ['newspaperguytear', 'http://i.imgur.com/Wtcl1XG.png'],
        ['no', 'http://i.imgur.com/HdDcgQ3.png'],
        ['notbad', 'http://i.imgur.com/Tocl7c0.jpg'],
        ['ogw', 'http://i.imgur.com/EZLdz9V.png'],
        ['ohno', 'http://i.imgur.com/TA9WruL.png'],
        ['okay', 'http://i.imgur.com/49KRrCu.png'],
        ['openmouth', 'http://i.imgur.com/5ZIvQ6e.png'],
        ['pffftcchchchhfffttt', 'http://i.imgur.com/IS0dcMz.png'],
        ['picard', 'http://i.imgur.com/on3efwD.png'],
        ['pokerface', 'http://i.imgur.com/aVbv7Eb.png'],
        ['popcorn', 'http://i.imgur.com/ZPwF1d9.gif'],
        ['problem', 'http://i.imgur.com/4YyBg1S.png'],
        ['racket', 'http://i.imgur.com/uAtTaHJ.jpg'],
        ['rage2', 'http://i.imgur.com/YdxqpSp.png'],
        ['redeyes', 'http://i.imgur.com/iD9SAMj.png'],
        ['sad', 'http://i.imgur.com/GRnnjlf.png'],
        ['sadmelvin', 'http://i.imgur.com/W5oScTm.png'],
        ['sadtroll', 'http://i.imgur.com/ZG2hPL0.png'],
        ['shaq', 'http://i.imgur.com/RL78dle.png'],
        ['shocked', 'http://i.imgur.com/nkXW4eU.png'],
        ['sidemouth', 'http://i.imgur.com/y2sd3oS.png'],
        ['smirk', 'http://i.imgur.com/zlwo5g6.jpg'],
        ['somuchwin', 'http://i.imgur.com/7nXovH0.png'],
        ['staredad', 'http://i.imgur.com/mkJCnqu.png'],
        ['steve', 'http://i.imgur.com/Pd4dNCX.jpg'],
        ['stfi', 'http://i.imgur.com/6g8g9o6.jpg'],
        ['suspicious', 'http://i.imgur.com/X1EKnGT.png'],
        ['tdadjump', 'http://i.imgur.com/qD5atiX.png'],
        ['thoughtful', 'http://i.imgur.com/mfz4H2d.png'],
        ['tongue', 'http://i.imgur.com/I7zH7a3.png'],
        ['trolldad', 'http://i.imgur.com/qOrL3Mo.png'],
        ['truestory', 'http://i.imgur.com/izwfP8h.png'],
        ['underbite', 'http://i.imgur.com/SUHKmoC.png'],
        ['wasted', 'http://i.imgur.com/CkSu9O6.png'],
        ['wat', 'http://i.imgur.com/7WjJFOz.jpg'],
        ['what', 'http://i.imgur.com/CGEo3ej.png'],
        ['whywithhands', 'http://i.imgur.com/4VRIr1C.png'],
        ['wizard', 'http://i.imgur.com/4Sc1dTa.png'],
        ['wut', 'http://i.imgur.com/OsNE9lV.png'],
        ['yaoming', 'http://i.imgur.com/w3awxbN.png'],
        ['yuno', 'http://i.imgur.com/Q381rgq.png']
    ],
    'Kolobok (ICQ)': [
        ["acute", "http://i.imgur.com/j6LrIBb.gif"],
        ["agressive", "http://i.imgur.com/enwmt9h.gif"],
        ["air_kiss", "http://i.imgur.com/ZP3on0U.gif"],
        ["angel", "http://i.imgur.com/X6IMyj3.gif"],
        ["bad", "http://i.imgur.com/xDVy0P3.gif"],
        ["bb2", "http://i.imgur.com/f4SEPlS.gif"],
        ["beach", "http://i.imgur.com/ToU8tbQ.gif"],
        ["bee", "http://i.imgur.com/RY0xC46.gif"],
        ["biggrin", "http://i.imgur.com/s3SOo3L.gif"],
        ["blueeye", "http://i.imgur.com/RGuZJXE.gif"],
        ["blum3", "http://i.imgur.com/KiRKoqx.gif"],
        ["blush", "http://i.imgur.com/RXZmaRB.gif"],
        ["blush2", "http://i.imgur.com/7H09LXw.gif"],
        ["boat", "http://i.imgur.com/pRynOh0.gif"],
        ["boredom", "http://i.imgur.com/kytNlQv.gif"],
        ["bye", "http://i.imgur.com/n7FSy7O.gif"],
        ["clapping", "http://i.imgur.com/zqQDs0k.gif"],
        ["cray", "http://i.imgur.com/wn37zSm.gif"],
        ["crazy", "http://i.imgur.com/FEJKMvE.gif"],
        ["im_king", "http://i.imgur.com/bwGYULL.gif"],
        ["welcome_sign", "http://i.imgur.com/c3Q9kDI.gif"],
        ["hug", "http://i.imgur.com/S9eEAmP.gif"],
        ["sweeet", "http://i.imgur.com/af6bU6w.gif"],
        ["dance", "http://i.imgur.com/GHKLDdS.gif"],
        ["dance22", "http://i.imgur.com/8j0VXTU.gif"],
        ["dance4", "http://i.imgur.com/bXoU0sM.gif"],
        ["dash2", "http://i.imgur.com/xC6Rhs5.gif"],
        ["diablo", "http://i.imgur.com/SQ4lIkt.gif"],
        ["dirol", "http://i.imgur.com/9lKwY5z.gif"],
        ["idk", "http://i.imgur.com/RzVFucM.gif"],
        ["dont_mention", "http://i.imgur.com/qHDPjUL.gif"],
        ["drinks", "http://i.imgur.com/k0yuQJN.gif"],
        ["friends", "http://i.imgur.com/vU4CUlF.gif"],
        ["girl_sigh", "http://i.imgur.com/zefYeBf.gif"],
        ["girl_wink", "http://i.imgur.com/fpDSxvP.gif"],
        ["give_heart", "http://i.imgur.com/l5yvmzm.gif"],
        ["give_rose", "http://i.imgur.com/52XMoK9.gif"],
        ["good", "http://i.imgur.com/qIL9Iuk.gif"],
        ["good3", "http://i.imgur.com/Ric3G1x.gif"],
        ["hahaha", "http://i.imgur.com/6UGUiQ2.gif"],
        ["hang1", "http://i.imgur.com/03To2P0.gif"],
        ["heart", "http://i.imgur.com/3DmaTab.gif"],
        ["heat", "http://i.imgur.com/w0ujgg8.gif"],
        ["sos_help", "http://i.imgur.com/g7o02u5.gif"],
        ["hyron_02", "http://i.imgur.com/fIEO19z.gif"],
        ["hysteric", "http://i.imgur.com/6tN0TUY.gif"],
        ["so_happy", "http://i.imgur.com/b6CoYVj.gif"],
        ["jc_dance", "http://i.imgur.com/7kvQWOS.gif"],
        ["doubleup", "http://i.imgur.com/oVAdEQt.gif"],
        ["goodpost", "http://i.imgur.com/7zMu6Uv.gif"],
        ["goody", "http://i.imgur.com/zgfSBcS.gif"],
        ["angry", "http://i.imgur.com/celQvj4.gif"],
        ["king", "http://i.imgur.com/NeVPPWl.gif"],
        ["kiss3", "http://i.imgur.com/7hzi60N.gif"],
        ["i_dance", "http://i.imgur.com/vX3byDD.gif"],
        ["laugh2", "http://i.imgur.com/hxk5UDp.gif"],
        ["lazy", "http://i.imgur.com/DONueKe.gif"],
        ["lazy2", "http://i.imgur.com/jSWDIHE.gif"],
        ["meeting", "http://i.imgur.com/UCwbgXw.gif"],
        ["music", "http://i.imgur.com/c9VZouO.gif"],
        ["nea", "http://i.imgur.com/zwEO3el.gif"],
        ["negative", "http://i.imgur.com/PivmUn6.gif"],
        ["slang_yo", "http://i.imgur.com/EK6nv26.gif"],
        ["nono", "http://i.imgur.com/llyDbEO.gif"],
        ["not_i", "http://i.imgur.com/zSCwyjI.gif"],
        ["ok", "http://i.imgur.com/5gJUq9D.gif"],
        ["paint", "http://i.imgur.com/UgZVBvh.gif"],
        ["paint2", "http://i.imgur.com/isEGYo5.gif"],
        ["pardon", "http://i.imgur.com/0zO0BZB.gif"],
        ["parting", "http://i.imgur.com/1hewhmf.gif"],
        ["party", "http://i.imgur.com/VOOqDrB.gif"],
        ["pleaseantry", "http://i.imgur.com/U8XIXXR.gif"],
        ["popcorn", "http://i.imgur.com/WzBFcFm.gif"],
        ["popcorn2", "http://i.imgur.com/N8r9ROo.gif"],
        ["punish", "http://i.imgur.com/VixLbza.gif"],
        ["read", "http://i.imgur.com/Ajbt8Ih.gif"],
        ["resent", "http://i.imgur.com/yEKwsmW.gif"],
        ["rtfm", "http://i.imgur.com/pESAEGu.gif"],
        ["snowball", "http://i.imgur.com/L5LLWj3.gif"],
        ["sad", "http://i.imgur.com/moJMX86.gif"],
        ["sarcastic", "http://i.imgur.com/Hf7MW5t.gif"],
        ["scare", "http://i.imgur.com/L0NpSPO.gif"],
        ["scare2", "http://i.imgur.com/0PbUF7F.gif"],
        ["senic", "http://i.imgur.com/qcXSACL.gif"],
        ["sclerosis", "http://i.imgur.com/TrnVFTi.gif"],
        ["think", "http://i.imgur.com/JGWSOEu.gif"],
        ["search", "http://i.imgur.com/rVeehgi.gif"],
        ["secret", "http://i.imgur.com/0wQVoaf.gif"],
        ["shok", "http://i.imgur.com/IMcYOBB.gif"],
        ["shout", "http://i.imgur.com/lQUhNtU.gif"],
        ["smile3", "http://i.imgur.com/4IF6yaq.gif"],
        ["smoke", "http://i.imgur.com/tdnOhKV.gif"],
        ["spiteful", "http://i.imgur.com/thJRHGO.gif"],
        ["spruce_up", "http://i.imgur.com/u0ybyPf.gif"],
        ["swoon", "http://i.imgur.com/Ced6tuN.gif"],
        ["swoon2", "http://i.imgur.com/V8wmmyl.gif"],
        ["tease", "http://i.imgur.com/moX4XOY.gif"],
        ["tender", "http://i.imgur.com/NS1qUDz.gif"],
        ["thank_you", "http://i.imgur.com/f6Zvd7E.gif"],
        ["this", "http://i.imgur.com/hF9cOcx.gif"],
        ["victory", "http://i.imgur.com/SY3d5p8.gif"],
        ["wacko", "http://i.imgur.com/SDfWo0f.gif"],
        ["wacko2", "http://i.imgur.com/M7hGj9Q.gif"],
        ["whistle", "http://i.imgur.com/JvBPglq.gif"],
        ["whistle2", "http://i.imgur.com/W4f9XMJ.gif"],
        ["wink", "http://i.imgur.com/i1EAQ5k.gif"],
        ["wink3", "http://i.imgur.com/meEgrtJ.gif"],
        ["yahoo", "http://i.imgur.com/moX4XOY.gif"],
        ["yes", "http://i.imgur.com/bzq896a.gif"]
    ],
    'Skype': [
        ['Finger', 'http://i.imgur.com/Vq4tnfX.png'],
        ['Bandit', 'http://i.imgur.com/HaE73Tn.png'],
        ['Drunk', 'http://i.imgur.com/cOW3MvB.png'],
        ['Smoking', 'http://i.imgur.com/6unXkzR.png'],
        ['Toivo', 'http://i.imgur.com/79s0lGz.png'],
        ['Rock', 'http://i.imgur.com/Y0dCJ3u.png'],
        ['Headbang', 'http://i.imgur.com/WcXHZi6.png'],
        ['Bug', 'http://i.imgur.com/mk8Gw5f.png'],
        ['Fubar', 'http://i.imgur.com/npCrTlu.png'],
        ['Poolparty', 'http://i.imgur.com/zBvkBgP.png'],
        ['Swearing', 'http://i.imgur.com/GcjD5fj.png'],
        ['TMI', 'http://i.imgur.com/mspnDLU.png'],
        ['Heidy', 'http://i.imgur.com/DKCHaw2.png'],
        ['Mooning', 'http://i.imgur.com/yMUAILh.png'],
        ['High Five', 'http://i.imgur.com/tXCG3uW.png'],
        ['Face Palm', 'http://i.imgur.com/vFuM5xA.png'],
        ['Fingers Crossed', 'http://i.imgur.com/M1Eg5ef.png'],
        ['Lalala', 'http://i.imgur.com/3JAitLU.png'],
        ['Waiting', 'http://i.imgur.com/5f2Wcm2.png'],
        ['Tumbleweed', 'http://i.imgur.com/LsfNlvh.png'],
        ['Working From Home', 'http://i.imgur.com/kRI8JhR.png'],
        ['Smile', 'http://i.imgur.com/3WHJDK8.png'],
        ['Sad Smile', 'http://i.imgur.com/H4ieTji.png'],
        ['Big Smile', 'http://i.imgur.com/QaxkvgL.png'],
        ['Cool', 'http://i.imgur.com/Gvw3pCJ.png'],
        ['Wink', 'http://i.imgur.com/m6MmVps.png'],
        ['Crying', 'http://i.imgur.com/TI4L2Pl.png'],
        ['Sweating', 'http://i.imgur.com/Jx6A13R.png'],
        ['Speechless', 'http://i.imgur.com/0B4GI6z.png'],
        ['Kiss', 'http://i.imgur.com/YmrF8fn.png'],
        ['Tongue Out', 'http://i.imgur.com/GzVsg5V.png'],
        ['Blush', 'http://i.imgur.com/30mN9BT.png'],
        ['Wondering', 'http://i.imgur.com/iqdLo7g.png'],
        ['Sleepy', 'http://i.imgur.com/EGIVG3t.png'],
        ['Dull', 'http://i.imgur.com/sqpO2B8.png'],
        ['In love', 'http://i.imgur.com/zE5DtVN.png'],
        ['Evil grin', 'http://i.imgur.com/n4m8ILM.gif'],
        ['Talking', 'http://i.imgur.com/RMqYJKp.gif'],
        ['Yawn', 'http://i.imgur.com/hr7bK78.gif'],
        ['Puke', 'http://i.imgur.com/IHuN5wl.gif'],
        ['Doh!', 'http://i.imgur.com/7wT15FV.gif'],
        ['Angry', 'http://i.imgur.com/dQ9YgfA.gif'],
        ['It wasn\'t me', 'http://i.imgur.com/3GdH5yC.gif'],
        ['Party!!!', 'http://i.imgur.com/1t42vCH.gif'],
        ['Worried', 'http://i.imgur.com/YPJlAeT.gif'],
        ['Mmm...', 'http://i.imgur.com/e7StHEb.gif'],
        ['Nerd', 'http://i.imgur.com/0bn86QN.gif'],
        ['Lips Sealed', 'http://i.imgur.com/GuslBRg.gif'],
        ['Hi', 'http://i.imgur.com/Z9qM8in.gif'],
        ['Call', 'http://i.imgur.com/MyVpfYu.gif'],
        ['Devil', 'http://i.imgur.com/lW4VdN8.gif'],
        ['Angel', 'http://i.imgur.com/Do7FhQh.gif'],
        ['Envy', 'http://i.imgur.com/axwcNzU.gif'],
        ['Wait', 'http://i.imgur.com/wVPXhM9.gif'],
        ['Bear', 'http://i.imgur.com/6sIlzyC.gif'],
        ['Make-up', 'http://i.imgur.com/UyDLehg.gif'],
        ['Covered Laugh', 'http://i.imgur.com/cjaROQx.gif'],
        ['Clapping Hands', 'http://i.imgur.com/WpdxGbB.gif'],
        ['Thinking', 'http://i.imgur.com/qe7CdHA.gif'],
        ['Bow', 'http://i.imgur.com/GUB4ciN.gif'],
        ['Rolling on the floor laughing', 'http://i.imgur.com/w3POgGA.gif'],
        ['Whew', 'http://i.imgur.com/mtpPDBB.gif'],
        ['Happy', 'http://i.imgur.com/vGVqaTJ.gif'],
        ['Smirking', 'http://i.imgur.com/ypbZPcd.gif'],
        ['Nodding', 'http://i.imgur.com/zupZhXz.gif'],
        ['Shaking', 'http://i.imgur.com/KimDZxP.gif'],
        ['Punch', 'http://i.imgur.com/2Em3BBS.gif'],
        ['Emo', 'http://i.imgur.com/3CsW8sK.gif'],
        ['Yes', 'http://i.imgur.com/5pAEze4.gif'],
        ['No', 'http://i.imgur.com/dN3cmR7.gif'],
        ['Shaking Hands', 'http://i.imgur.com/2c896ls.gif'],
        ['Skype', 'http://i.imgur.com/q5Y09kp.gif'],
        ['Heart', 'http://i.imgur.com/cZ1Xn7D.gif'],
        ['Broken heart', 'http://i.imgur.com/IyHUnee.gif'],
        ['Mail', 'http://i.imgur.com/EP8Sduz.gif'],
        ['Flower', 'http://i.imgur.com/r2HQLST.gif'],
        ['Rain', 'http://i.imgur.com/CYxKRuN.gif'],
        ['Sun', 'http://i.imgur.com/Ty8CyoQ.gif'],
        ['Time', 'http://i.imgur.com/PgoFjr5.gif'],
        ['Music', 'http://i.imgur.com/S45pmTi.gif'],
        ['Movie', 'http://i.imgur.com/9Yf6FHY.gif'],
        ['Phone', 'http://i.imgur.com/gL5yglU.gif'],
        ['Coffee', 'http://i.imgur.com/PTWTU7J.gif'],
        ['Pizza', 'http://i.imgur.com/YGi316s.gif'],
        ['Cash', 'http://i.imgur.com/6FgSKTW.gif'],
        ['Muscle', 'http://i.imgur.com/tMDUkBT.gif'],
        ['Cake', 'http://i.imgur.com/NhVive3.gif'],
        ['Beer', 'http://i.imgur.com/Xcc329B.gif'],
        ['Drink', 'http://i.imgur.com/dg6zocD.gif'],
        ['Dance', 'http://i.imgur.com/AigvYWH.gif'],
        ['Ninja', 'http://i.imgur.com/q7Kd13N.gif'],
        ['Star', 'http://i.imgur.com/eIHpD4Y.gif']
    ],
    'Y o l k s': [
        [';^^', 'http://i.imgur.com/Qj1jYUn.png'],
        ['¯ε¯¯', 'http://i.imgur.com/xMOJmab.png'],
        ['=B', 'http://i.imgur.com/VMCRUdi.png'],
        ['² z  Z ', 'http://i.imgur.com/Bp9cABV.png'],
        ['² z Z', 'http://i.imgur.com/ohrHsU5.png'],
        ['angry', 'http://i.imgur.com/Grie0Xg.png'],
        ['are you for real', 'http://i.imgur.com/DwtAAfc.png'],
        ['beaten', 'http://i.imgur.com/CybAOGz.png'],
        ['boo!', 'http://i.imgur.com/bowiEr8.png'],
        ['bouaaaaah', 'http://i.imgur.com/LiZXh1D.png'],
        ['brains...!', 'http://i.imgur.com/MVr8Ex0.png'],
        ['brzzzzz', 'http://i.imgur.com/1jMvc8N.png'],
        ['burnt', 'http://i.imgur.com/drCD5kY.png'],
        ['confident', 'http://i.imgur.com/DlYmbDk.png'],
        ['dark mood', 'http://i.imgur.com/DOwyBFs.png'],
        ['disapointed', 'http://i.imgur.com/SqPfzd1.png'],
        ['disappearing', 'http://i.imgur.com/zKDXsVa.png'],
        ['dizzy', 'http://i.imgur.com/R1czhwD.png'],
        ['enjoying mah playlist', 'http://i.imgur.com/dUeHciI.png'],
        ['evilish', 'http://i.imgur.com/BdY2DmG.png'],
        ['eyes on fire', 'http://i.imgur.com/qkYHEZw.png'],
        ['faill', 'http://i.imgur.com/ryNiJp2.png'],
        ['gangs', 'http://i.imgur.com/CZknUub.png'],
        ['graffiti', 'http://i.imgur.com/C8eP21s.png'],
        ['grin', 'http://i.imgur.com/vtPHuZP.png'],
        ['have a nice day', 'http://i.imgur.com/msFqr4A.png'],
        ['hidden', 'http://i.imgur.com/MXdDytN.png'],
        ['high', 'http://i.imgur.com/QzcbZir.png'],
        ['hope my fake smile works again', 'http://i.imgur.com/XNtSkB3.png'],
        ['ignoring', 'http://i.imgur.com/Ufwu3yU.png'],
        ['in love', 'http://i.imgur.com/zEC2JxN.png'],
        ['indifferent', 'http://i.imgur.com/nGqpIgH.png'],
        ['innocent', 'http://i.imgur.com/yXcWD0S.png'],
        ['ka boom', 'http://i.imgur.com/tmBnTf8.png'],
        ['lll._.', 'http://i.imgur.com/GwXgjQK.png'],
        ['mah (chilling)', 'http://i.imgur.com/qtZ54Qp.png'],
        ['meaw', 'http://i.imgur.com/99p1t55.png'],
        ['ninja', 'http://i.imgur.com/6GcvsdV.png'],
        ['nom nom', 'http://i.imgur.com/BFTlMoD.png'],
        ['nose bleed', 'http://i.imgur.com/gLMSBZM.png'],
        ['nose pick', 'http://i.imgur.com/gxy8J6V.png'],
        ['O_O', 'http://i.imgur.com/NFvz2ka.png'],
        ['oh noes', 'http://i.imgur.com/QRbiMkF.png'],
        ['oh u !', 'http://i.imgur.com/ZKotFhn.png'],
        ['omg', 'http://i.imgur.com/CXmdtje.png'],
        ['on fire 2', 'http://i.imgur.com/newPOXU.png'],
        ['on fire', 'http://i.imgur.com/ssA1wzR.png'],
        ['ouch...it hurts', 'http://i.imgur.com/lA4dlKP.png'],
        ['pissed off', 'http://i.imgur.com/AaY9Dpy.png'],
        ['psychotic', 'http://i.imgur.com/RisdVDa.png'],
        ['relief', 'http://i.imgur.com/vmoO40x.png'],
        ['scared', 'http://i.imgur.com/OB4xeF4.png'],
        ['secret laugh', 'http://i.imgur.com/iKPUbPY.png'],
        ['serious business', 'http://i.imgur.com/sWrOVkY.png'],
        ['shocked...again', 'http://i.imgur.com/XgLlbbl.png'],
        ['shocked', 'http://i.imgur.com/y3vtebE.png'],
        ['shout', 'http://i.imgur.com/Ju7aAL1.png'],
        ['shy', 'http://i.imgur.com/staWjia.png'],
        ['sick', 'http://i.imgur.com/0dm5qBR.png'],
        ['slow', 'http://i.imgur.com/QWti72X.png'],
        ['snooty', 'http://i.imgur.com/jzh5d4J.png'],
        ['tastey', 'http://i.imgur.com/1T6CnoW.png'],
        ['teeth brushing', 'http://i.imgur.com/Zr3F1Mv.png'],
        ['that dood is up to something', 'http://i.imgur.com/sVAexPd.png'],
        ['TT TT', 'http://i.imgur.com/oQMJ7eM.png'],
        ['want !', 'http://i.imgur.com/hbnMNs9.png'],
        ['want', 'http://i.imgur.com/6gRyjaP.png'],
        ['we all gonna die', 'http://i.imgur.com/Ql4O7Gf.png'],
        ['whisper', 'http://i.imgur.com/kjUpFs1.png'],
        ['whistle', 'http://i.imgur.com/MpEZ1yK.png'],
        ['wut', 'http://i.imgur.com/DDVX4dW.png'],
        ['x_x', 'http://i.imgur.com/6lbq7hQ.png'],
        ['X3', 'http://i.imgur.com/h3ptrWX.png'],
        ['XD', 'http://i.imgur.com/0QuZqED.png'],
        ['yaeh am not durnk', 'http://i.imgur.com/DBr5C09.png'],
        ['yarr', 'http://i.imgur.com/iGVDlMT.png'],
        ['yo !', 'http://i.imgur.com/RrkerJp.png'],
        ['you seem to be serious', 'http://i.imgur.com/FxqJvcm.png'],
        ['you\'re kidding, right', 'http://i.imgur.com/cLvlpOE.png'],
        ['yum', 'http://i.imgur.com/kyr2wtl.png'],
        ['yuush', 'http://i.imgur.com/G9dB8UQ.png']
    ],
    'Emojicons': [
        ['angry', 'http://i.imgur.com/fUiwRnr.png'],
        ['anguished', 'http://i.imgur.com/o27inQs.png'],
        ['astonished', 'http://i.imgur.com/TiaNfZ0.png'],
        ['blush', 'http://i.imgur.com/OC3Umql.png'],
        ['bowtie', 'http://i.imgur.com/UJ183ZD.png'],
        ['cold_sweat', 'http://i.imgur.com/nhiWJ4L.png'],
        ['confounded', 'http://i.imgur.com/VfhuYsP.png'],
        ['confused', 'http://i.imgur.com/4OJws4A.png'],
        ['cry', 'http://i.imgur.com/DPMIdlT.png'],
        ['disappointed', 'http://i.imgur.com/ulwFM48.png'],
        ['disappointed relieved', 'http://i.imgur.com/5Yz2Ghu.png'],
        ['dizzy face', 'http://i.imgur.com/LlZAi6y.png'],
        ['expressionless', 'http://i.imgur.com/CaMnWq2.png'],
        ['fearful', 'http://i.imgur.com/0tZMLYZ.png'],
        ['flushed', 'http://i.imgur.com/JEgIboY.png'],
        ['frowning', 'http://i.imgur.com/8RaAEA5.png'],
        ['grimacing', 'http://i.imgur.com/67JXuIP.png'],
        ['grin', 'http://i.imgur.com/Du4Doch.png'],
        ['grinning', 'http://i.imgur.com/ot0GDGa.png'],
        ['heart_eyes', 'http://i.imgur.com/Ny7xHQ1.png'],
        ['hushed', 'http://i.imgur.com/F3eoG7n.png'],
        ['innocent', 'http://i.imgur.com/bVrgTNN.png'],
        ['joy', 'http://i.imgur.com/ry1LQe6.png'],
        ['kissing', 'http://i.imgur.com/QVDdRiW.png'],
        ['kissing_closed_eyes', 'http://i.imgur.com/26TN3Hy.png'],
        ['kissing_heart', 'http://i.imgur.com/VPedYLl.png'],
        ['kissing_smiling_eyes', 'http://i.imgur.com/NjoCKUK.png'],
        ['laughing', 'http://i.imgur.com/KcQBfwH.png'],
        ['mask', 'http://i.imgur.com/WMpLNfy.png'],
        ['neckbeard', 'http://i.imgur.com/9WOHp0C.png'],
        ['neutral face', 'http://i.imgur.com/1OJZXtw.png'],
        ['no mouth', 'http://i.imgur.com/ms44N9K.png'],
        ['open mouth', 'http://i.imgur.com/mvvPb4B.png'],
        ['pensive', 'http://i.imgur.com/HuhQkNs.png'],
        ['persevere', 'http://i.imgur.com/ZCbzeOR.png'],
        ['rage', 'http://i.imgur.com/0pLfg6A.png'],
        ['relaxed', 'http://i.imgur.com/vvKoesU.png'],
        ['relieved', 'http://i.imgur.com/Gk3lc1W.png'],
        ['satisfied', 'http://i.imgur.com/Si1lLKV.png'],
        ['scream', 'http://i.imgur.com/9w1ekP7.png'],
        ['sleeping', 'http://i.imgur.com/SjmRavh.png'],
        ['sleepy', 'http://i.imgur.com/tnhQs79.png'],
        ['smile', 'http://i.imgur.com/VoBxxz1.png'],
        ['smiley', 'http://i.imgur.com/zMf3ZjF.png'],
        ['smirk', 'http://i.imgur.com/3vFOrQn.png'],
        ['sob', 'http://i.imgur.com/PyFII2u.png'],
        ['stuck out tongue', 'http://i.imgur.com/EWRKrDX.png'],
        ['stuck out tongue closed eyes', 'http://i.imgur.com/Zmji6Fw.png'],
        ['stuck out tongue winking eye', 'http://i.imgur.com/5uyMBJ3.png'],
        ['sunglasses', 'http://i.imgur.com/LZN38AO.png'],
        ['sweat', 'http://i.imgur.com/e0Jgvdj.png'],
        ['sweat smile', 'http://i.imgur.com/S73pDeI.png'],
        ['thumbsdown', 'http://i.imgur.com/SQfUD2S.png'],
        ['thumbsup', 'http://i.imgur.com/T3gKIkU.png'],
        ['tired face', 'http://i.imgur.com/9aIyd5A.png'],
        ['triumph', 'http://i.imgur.com/TWIkYvu.png'],
        ['unamused', 'http://i.imgur.com/waGTBzX.png'],
        ['weary', 'http://i.imgur.com/qTcFHIL.png'],
        ['wink', 'http://i.imgur.com/svggRUd.png'],
        ['worried', 'http://i.imgur.com/ZugxQVF.png'],
        ['yum', 'http://i.imgur.com/FTyoYkq.png']
    ]
};